export const ROUTES = {
    AUTH: {
        SPLASH: 'SplashScreen',
        ONBOARDING: 'OnboardingScreen',
        LOGIN: 'LoginScreen',
        REGISTER: 'RegisterScreen',
        PHONE_AUTH: 'PhoneAuthScreen',
        OTP_VERIFY: 'OTPVerifyScreen',
        EMAIL_VERIFY: 'EmailVerifyScreen',
        FORGOT_PASSWORD: 'ForgotPasswordScreen',
        ONBOARDING_STEPS: 'ProfileSetupScreen',
        INTERESTS: 'InterestsScreen',
        PERMISSIONS: 'PermissionsScreen',
    },
    MAIN: {
        HOME: 'HomeTab',
        CHAT: 'ChatTab',
        PROFILE: 'ProfileTab',
        NOTIFICATIONS: 'Notifications',
        FRIENDS: 'Friends',
        COMMUNITY: 'Community',
        SETTINGS: 'Settings',
        CHANGE_PASSWORD: 'ChangePassword',
        HELP_CENTER: 'HelpCenter',
        PRIVACY: 'Privacy',
        USER_DETAIL: 'UserDetail',
        QR_CODE: 'QRCode',
    },
    CHAT: {
        DIRECT: 'DirectMessage',
        NEW: 'NewMessage',
        CALL: 'Call',
    },
};
